import os
import shutil
from typing import Literal

import patoolib
from loguru import logger
from patoolib.util import PatoolError

from .utils import is_auto_generated


class ArchExtractor:
    """
    A class for extracting archive files, which wraps the patoolib library
    """

    @staticmethod
    def _validate_mode(mode: str) -> Literal["e", "x"]:
        if mode not in ("e", "x"):
            raise ValueError("Incorrect mode parameter")
        return mode  # type: ignore[return-value]

    @staticmethod
    def _unique_destination(dst: str, filename: str) -> str:
        dest_filepath = os.path.join(dst, filename)
        if not os.path.exists(dest_filepath):
            return dest_filepath

        basename, ext = os.path.splitext(filename)
        counter = 1
        while True:
            candidate = os.path.join(dst, f"{basename}({counter}){ext}")
            if not os.path.exists(candidate):
                return candidate
            counter += 1

    @staticmethod
    def _remove_auto_generated(dst: str) -> None:
        for root, dirs, files in os.walk(dst, topdown=True):
            for dirname in list(dirs):
                dirpath = os.path.join(root, dirname)
                if is_auto_generated(dirpath) and os.path.exists(dirpath):
                    shutil.rmtree(dirpath)
                    dirs.remove(dirname)
                    logger.info(
                        f"Removed the file {dirpath} because it is auto generated by the system or tool"
                    )
            for file in files:
                filepath = os.path.join(root, file)
                if is_auto_generated(filepath) and os.path.exists(filepath):
                    os.remove(filepath)
                    logger.info(
                        f"Removed the file {filepath} because it is auto generated by the system or tool"
                    )

    def test_archive(
        self,
        src: str,
        verbosity: int = 0,
        program: str | None = None,
        interactive: bool = False,
        password: str | None = None,
    ) -> bool:
        """
        Test if the file is a valid archive file, two steps:
        1. Preliminarily judge whether a file is a compressed package based on the file suffix (rough screening)
        2. Further check whether the compressed file exists or is a regular file (fine screening)

        Args:
            src (str): The source path of the archive file (only file path, not directory path).
            verbosity (int, optional): See `patoolib.test_archive` for more details. Defaults to 0.
            program (str | None, optional): See `patoolib.test_archive` for more details. Defaults to None.
            interactive (bool, optional): See `patoolib.test_archive` for more details. Defaults to False.
            password (str | None, optional): See `patoolib.test_archive` for more details. Defaults to None.

        Returns:
            bool: True if the file is a valid archive file, False otherwise
        """
        # 根据文件后缀名初步判断文件是否是压缩包（粗筛）
        if not patoolib.is_archive(src):
            logger.error(f"The file {src} is not a valid archive file")
            return False

        try:
            # 进一步检查压缩文件是否存在或者为常规文件（精筛）
            #!将会进一步排除在粗筛中未过滤的不能解压的文件类型
            #!常见的例子是，这些压缩文件以受支持的压缩文件扩展名为结尾，但本身不是压缩文件（eg. .flac）或压缩包损坏而导致无法解压
            patoolib.test_archive(
                src,
                verbosity=verbosity,
                program=program,
                interactive=interactive,
                password=password,
            )

        except PatoolError as exc:
            logger.error(
                f"Failed to test the archive file {src}: {exc.__class__.__name__}: {exc}"
            )
            return False

        return True

    def extractall(
        self,
        src: str,
        dst: str,
        mode: Literal["e", "x"] = "x",
        verbosity: int = 0,
        program: str | None = None,
        interactive: bool = False,
        password: str | None = None,
        cleanup: bool = False,
    ):
        """
        Extract all the archive files in the source path, including the nested archive files.

        If the cleanup parameter is provided as True, the source archive file will be deleted after extraction.

        Note:
            It will preserve the complete original directory structure of the extracted files.

        Args:
            src (str): The source path of the archive file (only file path, not directory path).
            dst (str): The destination path of the extracted files (only directory path, not file path).
            mode (Literal["e", "x"], optional): The mode of the extraction. Defaults to "x". If set to "e", the extracted files will be moved to the top level directory. If set to "x", the extracted files will be kept in the original directory structure.
            verbosity (int, optional): See `patoolib.extract_archive` for more details. Defaults to 0.
            program (str | None, optional): See `patoolib.extract_archive` for more details. Defaults to None.
            interactive (bool, optional): See `patoolib.extract_archive` for more details. Defaults to False.
            password (str | None, optional): See `patoolib.extract_archive` for more details. Defaults to None.
            cleanup (bool, optional): If the cleanup parameter is provided as True, the source archive file will be deleted after extraction. Defaults to False.
        """
        mode = self._validate_mode(mode)

        # 提取顶层压缩包
        if (
            self.extract(
                src=src,
                dst=dst,
                mode="x",
                verbosity=verbosity,
                program=program,
                interactive=interactive,
                password=password,
                cleanup=False,
            )
            is None
        ):
            return None

        processed_archives = {os.path.realpath(src)}

        # 扫描实际输出目录，而不是按压缩包文件名推断目录。压缩包可以直接
        # 在输出目录顶层释放文件，也可以释放和文件名无关的顶层目录。
        while True:
            extracted_nested_archive = False
            for root, dirs, files in os.walk(dst):
                for file in files:
                    sub_file = os.path.join(root, file)
                    real_sub_file = os.path.realpath(sub_file)
                    if real_sub_file in processed_archives:
                        continue
                    if not patoolib.is_archive(sub_file):
                        continue
                    result = self.extract(
                        src=sub_file,
                        dst=os.path.dirname(sub_file),
                        mode="x",
                        verbosity=verbosity,
                        program=program,
                        interactive=interactive,
                        password=password,
                        cleanup=cleanup,
                    )
                    if result is None:
                        return None
                    processed_archives.add(real_sub_file)
                    extracted_nested_archive = True
            if not extracted_nested_archive:
                break

        if mode == "e":
            self.flatten(dst=dst)

        if cleanup and os.path.exists(src):
            os.remove(src)
            logger.info(f"Removed the file {src} because cleanup is enabled")

        return dst

    def extract(
        self,
        src: str,
        dst: str,
        mode: Literal["e", "x"] = "x",
        verbosity: int = 0,
        program: str | None = None,
        interactive: bool = False,
        password: str | None = None,
        cleanup: bool = False,
    ) -> str | None:
        """
        Extract the archive file in the source path, but do not include nested archive files.

        If the cleanup parameter is provided as True, the source archive file will be deleted after extraction.

        Note:
            It will preserve the complete original directory structure of the extracted files.

        Args:
            src (str): The source path of the archive file (only file path, not directory path).
            dst (str): The destination path of the extracted files (only directory path, not file path).
            mode (Literal["e", "x"], optional): The mode of the extraction. Defaults to "x". If set to "e", the extracted files will be moved to the top level directory. If set to "x", the extracted files will be kept in the original directory structure.
            verbosity (int, optional): See `patoolib.extract_archive` for more details. Defaults to 0.
            program (str | None, optional): See `patoolib.extract_archive` for more details. Defaults to None.
            interactive (bool, optional): See `patoolib.extract_archive` for more details. Defaults to False.
            password (str | None, optional): See `patoolib.extract_archive` for more details. Defaults to None.
            cleanup (bool, optional): If the cleanup parameter is provided as True, the source archive file will be deleted after extraction. Defaults to False.
        """
        mode = self._validate_mode(mode)

        # 测试该压缩包是否可解压
        if not self.test_archive(
            src=src,
            verbosity=verbosity,
            program=program,
            interactive=interactive,
            password=password,
        ):
            return

        try:
            # 尝试提取该压缩文件
            # patool 会返回真实的解压目标路径；调用方可以用它判断本次解压是否成功。
            extracted_path = patoolib.extract_archive(
                src,
                outdir=dst,
                verbosity=verbosity,
                program=program,
                interactive=interactive,
                password=password,
            )

        except PatoolError as exc:
            logger.error(
                f"Failed to extract the archive file {src}: {exc.__class__.__name__}: {exc}"
            )
            return None

        try:
            # 删除由操作系统或工具自动生成的文件夹/文件
            self._remove_auto_generated(dst)

            if mode == "e":
                self.flatten(dst=dst)

            # 只有在 patool 解压成功并完成后处理后，才删除源压缩包。
            if cleanup and os.path.exists(src):
                os.remove(src)
                logger.info(f"Removed the file {src} because cleanup is enabled")

        except OSError as exc:
            logger.error(
                f"Failed to perform file-level operations: {exc.__class__.__name__}: {exc}"
            )

        return extracted_path

    def flatten(
        self,
        dst: str,
    ):
        """
        Flatten the extracted files, remove the original directory structure and move all files to the top level directory.

        Args:
            dst (str): The destination path of the flattened files (only directory path, not file path).
        """
        try:
            # 将所有文件移动到顶层目录，并从深至浅清理空目录。只移动文件，
            # 避免同名目录和文件冲突时把文件塞进已有目录。
            for root, dirs, files in os.walk(dst, topdown=False):
                # 跳过已经在顶层目录的文件
                if root == dst:
                    continue
                for filename in files:
                    # 如果目标路径已存在，处理文件/目录名称冲突（重命名）
                    dest_filepath = self._unique_destination(dst, filename)
                    shutil.move(os.path.join(root, filename), dest_filepath)
                try:
                    os.rmdir(root)
                except OSError:
                    pass

        except OSError as exc:
            logger.error(
                f"Failed to perform file-level operations: {exc.__class__.__name__}: {exc}"
            )
