import os
import shutil
from typing import Literal

import patoolib
from loguru import logger
from patoolib.util import PatoolError

from .utils import is_auto_generated


class ArchExtractor:
    """
    Stateless archive extractor built on top of patool.

    Each operation receives explicit ``src`` and ``dst`` paths, so the same instance can be reused for multiple unrelated archives.

    Public API:
        - ``test_archive(src, ...)``: Validate whether an archive can be processed by patool.
        - ``extract(src, dst, ...)``: Extract one archive without recursively processing nested archives.
        - ``extractall(src, dst, ...)``: Extract one archive and recursively extract nested archives found in the output tree.

    Internal helpers:
        Methods whose names start with ``_`` are implementation details used by the public API and should not be called directly by consumers.
    """

    @staticmethod
    def _validate_mode(mode: str) -> Literal["e", "x"]:
        """
        Validate and normalize the extraction mode.

        Args:
            mode (str): Extraction mode. ``"x"`` preserves directory structure. ``"e"`` flattens extracted files into the destination directory.

        Returns:
            Literal["e", "x"]: The validated mode.

        Raises:
            ValueError: If ``mode`` is not ``"e"`` or ``"x"``.
        """
        if mode not in ("e", "x"):
            raise ValueError("Incorrect mode parameter")
        return mode  # type: ignore[return-value]

    @staticmethod
    def _unique_destination(dst: str, filename: str) -> str:
        """
        Return a non-existing destination path for a flattened file.

        If ``filename`` already exists as either a file or directory under ``dst``, a numeric suffix is appended before the extension.

        Args:
            dst (str): Destination directory.
            filename (str): Original file name to move into ``dst``.

        Returns:
            str: A path under ``dst`` that does not currently exist.
        """
        dest_filepath = os.path.join(dst, filename)
        if not os.path.exists(dest_filepath):
            return dest_filepath

        basename, ext = os.path.splitext(filename)
        counter = 1
        while True:
            candidate = os.path.join(dst, f"{basename}({counter}){ext}")
            if not os.path.exists(candidate):
                return candidate
            counter += 1

    @staticmethod
    def _remove_auto_generated(dst: str) -> None:
        """
        Remove known OS/tool-generated files from an extracted tree.

        Args:
            dst (str): Root directory to scan and clean.
        """
        for root, dirs, files in os.walk(dst, topdown=True):
            for dirname in list(dirs):
                dirpath = os.path.join(root, dirname)
                if is_auto_generated(dirpath) and os.path.exists(dirpath):
                    shutil.rmtree(dirpath)
                    dirs.remove(dirname)
                    logger.info(
                        f"Removed the file {dirpath} because it is auto generated by the system or tool"
                    )
            for file in files:
                filepath = os.path.join(root, file)
                if is_auto_generated(filepath) and os.path.exists(filepath):
                    os.remove(filepath)
                    logger.info(
                        f"Removed the file {filepath} because it is auto generated by the system or tool"
                    )

    def test_archive(
        self,
        src: str,
        verbosity: int = 0,
        program: str | None = None,
        interactive: bool = False,
        password: str | None = None,
    ) -> bool:
        """
        Test whether ``src`` is a readable archive supported by patool.

        The check has two stages:

        1. Use patool's archive-name detection as a quick suffix/format screen (rough screening).
        2. Ask patool to test the archive with the selected backend program (fine screening).

        Args:
            src (str): The source path of the archive file (only file path, not directory path).
            verbosity (int, optional): Larger values print more information. 0 is the default, -1 or lower means no output, values >= 1 prints command output. Defaults to 0.
            program (str | None, optional): If None (the default), a list of suitable archive programs are checked if they exist in the system search path (defined by the PATH environment variable). If a program name is given, it is added to the list of programs that is searched for. The program should be a relative or absolute path name to an executable. Defaults to None.
            interactive (bool, optional): If True, wait for user input if the extraction program asks for it. This should be set to True if you intend to type in a password interactively. If set to False, standard input will be set to an empty string to prevent simple hangs from programs requiring input. Defaults to False.
            password (str | None, optional): If an archive is encrypted, set the given password with command line options. Note that the password might be written to logs that keep track of your command line history. If an archive program does not support passwords this option is ignored by patool. Defaults to None.

        Returns:
            bool: ``True`` when patool accepts and tests the archive successfully (processable archive files). ``False`` when detection or backend validation fails (unprocessable archive files).
        """

        # 根据文件后缀名初步判断文件是否是压缩包（粗筛）
        if not patoolib.is_archive(src):
            logger.error(f"The file {src} is not a valid archive file")
            return False

        try:
            # 进一步检查压缩文件是否存在或者为常规文件（精筛）
            #!将会进一步排除在粗筛中未过滤的不能解压的文件类型
            #!常见的例子是，这些压缩文件以受支持的压缩文件扩展名为结尾，但本身不是压缩文件（eg. .flac）或压缩包损坏而导致无法解压
            patoolib.test_archive(
                src,
                verbosity=verbosity,
                program=program,
                interactive=interactive,
                password=password,
            )

        except PatoolError as exc:
            logger.error(
                f"Failed to test the archive file {src}: {exc.__class__.__name__}: {exc}"
            )
            return False

        return True

    def extractall(
        self,
        src: str,
        dst: str,
        mode: Literal["e", "x"] = "x",
        verbosity: int = 0,
        program: str | None = None,
        interactive: bool = False,
        password: str | None = None,
        cleanup: bool = False,
    ) -> str | None:
        """
        Extract ``src`` and recursively extract nested archives found under ``dst``.

        Note:
            ``mode="x"`` preserves the complete original directory structure of the extracted files.

            ``mode="e"`` first extracts every nested archive, then flattens all extracted files into ``dst`` and removes empty directories.

            When ``cleanup=True``, the top-level source archive is removed only after every archive extraction in the recursive pass returns successfully.

            Nested archives are removed after their own successful extraction.

        Args:
            src (str): The source path of the archive file (only file path, not directory path).
            dst (str): The destination path of the extracted files (only directory path, not file path).
            mode (Literal["e", "x"], optional): The mode of the extraction. Defaults to "x". If set to "e", the extracted files will be moved to the top level directory. If set to "x", the extracted files will be kept in the original directory structure.
            verbosity (int, optional): Larger values print more information. 0 is the default, -1 or lower means no output, values >= 1 prints command output. Defaults to 0.
            program (str | None, optional): If None (the default), a list of suitable archive programs are checked if they exist in the system search path (defined by the PATH environment variable). If a program name is given, it is added to the list of programs that is searched for. The program should be a relative or absolute path name to an executable. Defaults to None.
            interactive (bool, optional): If True, wait for user input if the extraction program asks for it. This should be set to True if you intend to type in a password interactively. If set to False, standard input will be set to an empty string to prevent simple hangs from programs requiring input. Defaults to False.
            password (str | None, optional): If an archive is encrypted, set the given password with command line options. Note that the password might be written to logs that keep track of your command line history. If an archive program does not support passwords this option is ignored by patool. Defaults to None.
            cleanup (bool, optional): If the cleanup parameter is provided as True, the source archive file will be deleted after extraction. Defaults to False.

        Returns:
            str | None: ``dst`` when the top-level archive and every nested archive are extracted successfully. ``None`` if any archive validation or extraction step fails.

        Raises:
            ValueError: If ``mode`` is not ``"e"`` or ``"x"``.
        """

        mode = self._validate_mode(mode)

        # 提取顶层压缩包
        if (
            self.extract(
                src=src,
                dst=dst,
                mode="x",
                verbosity=verbosity,
                program=program,
                interactive=interactive,
                password=password,
                cleanup=False,
            )
            is None
        ):
            return None

        processed_archives = {os.path.realpath(src)}

        # 扫描实际输出目录，而不是按压缩包文件名推断目录。压缩包可以直接
        # 在输出目录顶层释放文件，也可以释放和文件名无关的顶层目录。
        while True:
            extracted_nested_archive = False
            for root, dirs, files in os.walk(dst):
                for file in files:
                    sub_file = os.path.join(root, file)
                    real_sub_file = os.path.realpath(sub_file)
                    if real_sub_file in processed_archives:
                        continue
                    if not patoolib.is_archive(sub_file):
                        continue
                    result = self.extract(
                        src=sub_file,
                        dst=os.path.dirname(sub_file),
                        mode="x",
                        verbosity=verbosity,
                        program=program,
                        interactive=interactive,
                        password=password,
                        cleanup=cleanup,
                    )
                    if result is None:
                        return None
                    processed_archives.add(real_sub_file)
                    extracted_nested_archive = True
            if not extracted_nested_archive:
                break

        if mode == "e":
            self._flatten(dst=dst)

        if cleanup and os.path.exists(src):
            os.remove(src)
            logger.info(f"Removed the file {src} because cleanup is enabled")

        return dst

    def extract(
        self,
        src: str,
        dst: str,
        mode: Literal["e", "x"] = "x",
        verbosity: int = 0,
        program: str | None = None,
        interactive: bool = False,
        password: str | None = None,
        cleanup: bool = False,
    ) -> str | None:
        """
        Extract a single archive without recursively processing nested archives.

        Note:
            ``mode="x"`` preserves the complete original directory structure of the extracted files.

            ``mode="e"`` flattens the files produced by this extraction into ``dst``.

            When ``cleanup=True``, ``src`` is removed only after patool extraction succeeds and the cleanup step is reached.

        Args:
            src (str): The source path of the archive file (only file path, not directory path).
            dst (str): The destination path of the extracted files (only directory path, not file path).
            mode (Literal["e", "x"], optional): The mode of the extraction. Defaults to "x". If set to "e", the extracted files will be moved to the top level directory. If set to "x", the extracted files will be kept in the original directory structure.
            verbosity (int, optional): Larger values print more information. 0 is the default, -1 or lower means no output, values >= 1 prints command output. Defaults to 0.
            program (str | None, optional): If None (the default), a list of suitable archive programs are checked if they exist in the system search path (defined by the PATH environment variable). If a program name is given, it is added to the list of programs that is searched for. The program should be a relative or absolute path name to an executable. Defaults to None.
            interactive (bool, optional): If True, wait for user input if the extraction program asks for it. This should be set to True if you intend to type in a password interactively. If set to False, standard input will be set to an empty string to prevent simple hangs from programs requiring input. Defaults to False.
            password (str | None, optional): If an archive is encrypted, set the given password with command line options. Note that the password might be written to logs that keep track of your command line history. If an archive program does not support passwords this option is ignored by patool. Defaults to None.
            cleanup (bool, optional): If the cleanup parameter is provided as True, the source archive file will be deleted after extraction. Defaults to False.

        Returns:
            str | None: The directory where the archive has been extracted (returned by ``patoolib.extract_archive``) when extraction succeeds. ``None`` when validation or extraction fails.

        Raises:
            ValueError: If ``mode`` is not ``"e"`` or ``"x"``.
        """

        mode = self._validate_mode(mode)

        # 测试该压缩包是否可解压
        if not self.test_archive(
            src=src,
            verbosity=verbosity,
            program=program,
            interactive=interactive,
            password=password,
        ):
            return None

        try:
            # 尝试提取该压缩文件
            # patool 会返回真实的解压目标路径；调用方可以用它判断本次解压是否成功。
            extracted_path = patoolib.extract_archive(
                src,
                outdir=dst,
                verbosity=verbosity,
                program=program,
                interactive=interactive,
                password=password,
            )

        except PatoolError as exc:
            logger.error(
                f"Failed to extract the archive file {src}: {exc.__class__.__name__}: {exc}"
            )
            return None

        try:
            # 删除由操作系统或工具自动生成的文件夹/文件
            self._remove_auto_generated(dst)

            if mode == "e":
                self._flatten(dst=dst)

            # 只有在 patool 解压成功并完成后处理后，才删除源压缩包。
            if cleanup and os.path.exists(src):
                os.remove(src)
                logger.info(f"Removed the file {src} because cleanup is enabled")

        except OSError as exc:
            logger.error(
                f"Failed to perform file-level operations: {exc.__class__.__name__}: {exc}"
            )

        return extracted_path

    def _flatten(
        self,
        dst: str,
    ) -> None:
        """
        Flatten extracted files into ``dst`` and remove empty directories.

        Files whose names conflict with existing files or directories in ``dst`` are renamed with a numeric suffix.

        Args:
            dst (str): The destination path of the flattened files (only directory path, not file path).

        Returns:
            None
        """
        try:
            # 将所有文件移动到顶层目录，并从深至浅清理空目录。只移动文件，
            # 避免同名目录和文件冲突时把文件塞进已有目录。
            for root, dirs, files in os.walk(dst, topdown=False):
                # 跳过已经在顶层目录的文件
                if root == dst:
                    continue
                for filename in files:
                    # 如果目标路径已存在，处理文件/目录名称冲突（重命名）
                    dest_filepath = self._unique_destination(dst, filename)
                    shutil.move(os.path.join(root, filename), dest_filepath)
                try:
                    os.rmdir(root)
                except OSError:
                    pass

        except OSError as exc:
            logger.error(
                f"Failed to perform file-level operations: {exc.__class__.__name__}: {exc}"
            )
